{1, "INSERT INTO answers (id, sentence) VALUES (?, 'As I see it, yes');"},
{2, "INSERT INTO answers (id, sentence) VALUES (?, 'It is certain');"},
{3, "INSERT INTO answers (id, sentence) VALUES (?, 'It is decidedly so');"},
{4, "INSERT INTO answers (id, sentence) VALUES (?, 'Most likely');"},
{5, "INSERT INTO answers (id, sentence) VALUES (?, 'Yes');"},
{6, "INSERT INTO answers (id, sentence) VALUES (?, 'Ask again later');"},
{7, "INSERT INTO answers (id, sentence) VALUES (?, 'Better not tell you now');"},
{8, "INSERT INTO answers (id, sentence) VALUES (?, 'Cannot predict now');"},
{9, "INSERT INTO answers (id, sentence) VALUES (?, 'Reply hazy, try again');"},
{10, "INSERT INTO answers (id, sentence) VALUES (?, 'Concentrate and ask again');"},
{11, "INSERT INTO answers (id, sentence) VALUES (?, 'Do not count on it');"},
{12, "INSERT INTO answers (id, sentence) VALUES (?, 'My reply is no');"},
{13, "INSERT INTO answers (id, sentence) VALUES (?, 'My sources say no');"},
{14, "INSERT INTO answers (id, sentence) VALUES (?, 'Outlook not so good');"},
{15, "INSERT INTO answers (id, sentence) VALUES (?, 'Very doubtful');"}
